### ISSUE TITLE
TypeError: to_csv() got an unexpected keyword argument 'cols'

### ISSUE THREAD

**Issue by boydthomson** [jyunfan/poloniex-data#2]
running this in a terminal, I get the following failure:
Traceback (most recent call last):
  File "getdata.py", line 60, in <module>
    main()
  File "getdata.py", line 56, in main
    get_data(pair)
  File "getdata.py", line 39, in get_data
    df.to_csv(outf, index=False, cols=COLUMNS)
TypeError: to_csv() got an unexpected keyword argument 'cols'

Running in VS Code I get more:
Traceback (most recent call last):
  File "/home/boyd/dev/poloniex-data/getdata.py", line 60, in <module>
    main()
  File "/home/boyd/dev/poloniex-data/getdata.py", line 56, in main
    get_data(pair)
  File "/home/boyd/dev/poloniex-data/getdata.py", line 25, in get_data
    df = pd.read_json(url, convert_dates=False)
  File "/home/boyd/.local/lib/python3.5/site-packages/pandas/io/json/json.py", line 322, in read_json
    encoding=encoding)
  File "/home/boyd/.local/lib/python3.5/site-packages/pandas/io/common.py", line 191, in get_filepath_or_buffer
    reader = BytesIO(req.read())
  File "/usr/lib/python3.5/http/client.py", line 455, in read
    return self._readall_chunked()
  File "/usr/lib/python3.5/http/client.py", line 565, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(363903 bytes read)

**Comment by burgerbaba** [comment]
Change "cols" argument to "columns".

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html
shows that related argument is columns, not cols.
